In [5]:
import tensorflow as tf

### Tensors
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." 

Every tensor has a:
- Datatype
- Shape
- Rank/degree = the number of dimensions it has.

In [23]:
# Tensor ranks and shapes
scalar = tf.Variable("this is a string", tf.string) 
print("scalar rank =", tf.rank(scalar))
print("scalar shape =", scalar.shape)

rank_1 = tf.Variable(["beep", "boop"], tf.string)
print("rank_1 =", tf.rank(rank_1))
print("rank_1 shape =", rank_1.shape)

rank_2 = tf.Variable([["beep", "boop"],["electric", "boogaloo"]], tf.string)
print("rank_2 (matrix) =", tf.rank(rank_2))
print("rank_2 shape =", rank_2.shape)

scalar rank = tf.Tensor(0, shape=(), dtype=int32)
scalar shape = ()
rank_1 = tf.Tensor(1, shape=(), dtype=int32)
rank_1 shape = (2,)
rank_2 (matrix) = tf.Tensor(2, shape=(), dtype=int32)
rank_2 shape = (2, 2)


In [33]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [36]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

print(tensor[0]) # selects the first row
 
print(tensor[:, 0]) # first column

print(tensor[1::2]) # second and fourth row
 
print(tensor[1:3, 0]) # column 1 for rows 2 and 3

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
